const mongoose = require('mongoose');

// SRS Module 9 - the seven kinds of material the Resource Library covers.
// Order matters: the UI renders filter tabs in this order.
const TYPES = [
  'notes',
  'paper',
  'template',
  'book',
  'roadmap',
  'interview',
  'cheatsheet',
];

const resourceSchema = new mongoose.Schema(
  {
    uploadedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: true,
      index: true,
    },

    type: { type: String, enum: TYPES, required: true, index: true },
    title: { type: String, required: true, trim: true, maxlength: 200 },
    description: { type: String, default: '', maxlength: 3000 },

    // What it's for, in the words a student would search: "Data Structures",
    // "Semester 4", "SDE intern". Free text because course naming is per
    // institution and an enum would be wrong everywhere but one campus.
    subject: { type: String, default: '', trim: true, maxlength: 120, index: true },

    tags: { type: [String], default: [], index: true },

    // A resource is either a link out or a file we host. Enforced in the
    // controller rather than by schema validators so the message can say which
    // one is missing.
    link: { type: String, default: '', maxlength: 500 },
    file: {
      type: {
        // Generated by the upload middleware. Never user-supplied, and the only
        // thing that is ever joined onto a filesystem path.
        storedName: String,
        // What it was called when uploaded. A display label only.
        originalName: String,
        sizeBytes: Number,
        mimeType: String,
      },
      default: null,
    },

    // Voters stored by id rather than as a counter, so a user cannot vote twice
    // and we can tell the caller how *they* voted — the same shape the forum
    // uses for threads and comments.
    upvotes: { type: [mongoose.Schema.Types.ObjectId], ref: 'User', default: [] },
    downvotes: { type: [mongoose.Schema.Types.ObjectId], ref: 'User', default: [] },

    downloadCount: { type: Number, default: 0 },
  },
  { timestamps: true }
);

// Free-text search over the fields people actually search by.
resourceSchema.index({ title: 'text', description: 'text', subject: 'text' });

resourceSchema.methods.score = function () {
  return this.upvotes.length - this.downvotes.length;
};

const userRef = (value) =>
  value && value._id
    ? { id: value._id, name: value.name, role: value.role, avatarUrl: value.avatarUrl }
    : value;

resourceSchema.methods.toPublicJSON = function (viewer = {}) {
  const viewerId = viewer.userId ? String(viewer.userId) : null;

  return {
    id: this._id,
    uploadedBy: userRef(this.uploadedBy),
    type: this.type,
    title: this.title,
    description: this.description,
    subject: this.subject,
    tags: this.tags,
    link: this.link,
    // The stored name never leaves the server — a client that knew it would be
    // one path-join away from the filesystem. Downloads go through the id.
    file: this.file
      ? {
          originalName: this.file.originalName,
          sizeBytes: this.file.sizeBytes,
          mimeType: this.file.mimeType,
        }
      : null,
    hasFile: Boolean(this.file),
    score: this.score(),
    downloadCount: this.downloadCount,
    createdAt: this.createdAt,
    updatedAt: this.updatedAt,
    // Viewer-specific state, resolved per request rather than stored here.
    myVote: !viewerId
      ? 0
      : this.upvotes.some((id) => String(id) === viewerId)
        ? 1
        : this.downvotes.some((id) => String(id) === viewerId)
          ? -1
          : 0,
    saved: Boolean(viewer.saved),
    canManage: Boolean(viewer.canManage),
  };
};

module.exports = mongoose.model('Resource', resourceSchema);
module.exports.TYPES = TYPES;
